name: Get Cat Fact
run-name: Meow! 
on:
  schedule:
    - cron: "15 17 17 12 *"
jobs:
  Get-Cat-Fact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python main.py
